spring.application.name=task
server.port=8081

app.bootstrap.admin-email=admin@assessment.local
app.bootstrap.admin-password=Admin123!
app.bootstrap.admin-name=System Admin
app.bootstrap.analyst-email=analyst@assessment.local
app.bootstrap.analyst-password=Analyst123!
app.bootstrap.analyst-name=System Analyst

spring.datasource.url=jdbc:postgresql://localhost:5433/assessment
spring.datasource.username=assessment
spring.datasource.password=assessment
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

